# -*- coding: utf-8 -*-
"""Pack book/*.md into book-content.js for offline / file:// use."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BOOK = ROOT / "book"
OUT = ROOT / "book-content.js"


def main() -> None:
    files = sorted(BOOK.glob("*.md"))
    if not files:
        raise SystemExit(f"No markdown files in {BOOK}")

    payload = {}
    for f in files:
        payload[f.name] = f.read_text(encoding="utf-8")

    # json.dumps gives valid JS string literals
    body = json.dumps(payload, ensure_ascii=False, indent=2)
    out = (
        "/* auto-generated by scripts/build_book.py — do not edit by hand */\n"
        "/* source: book/*.md */\n"
        f"const CHAPTER_TEXT = {body};\n"
    )
    OUT.write_text(out, encoding="utf-8")
    total = sum(len(v) for v in payload.values())
    print(f"Wrote {OUT.name}: {len(payload)} chapters, {total} chars")


if __name__ == "__main__":
    main()
